# Generated by Django 3.1.2 on 2021-02-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210129_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
    ]
